version: "3.7"
services:
  webapp:
    build: .
    ports:
      - "8000"
    deploy:
      mode: replicated
      replicas: 3

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - webapp
    depends_on:
      - webapp
    ports:
      - "4000:4000"